# Generated by Django 6.0.1 on 2026-02-06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Prefer not to say')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('student_code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('expelled', 'Expelled'), ('transferred', 'Transferred'), ('graduated', 'Graduated')], max_length=15)),
                ('enrollment_date', models.DateField()),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_phone', models.CharField(max_length=15)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('guardian_relation', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
